### ISSUE TITLE
Support multiple event handler (ready, onmessage)

### ISSUE THREAD

**Issue by jerryc-nguyen** [azuqua/token-sockjs-client#10]
Hi, 
First of all, I want to say thanks for your wonderful pub/sub  realtime websocket. It's played well on almost application part. Today, I meet issue on register handler for the ready and onmessage event with the tokensock instance.
Let me describe the problem:
First, I init the global tokensock instance like your example.
Then It's worked well when I register only once handler for ready event like this:
self.socket.ready (error) ->
            throw Error(JSON.stringify(error)) if error
            self.initRealtimeService()
But for my app design, we need the realtime on chat central admin page (using angularjs to handle) and the sidebar on others page (also on the chat admin page). But the sidebar not using angularjs. So I decice to register more handler to ready then onmessage event to display the message received from the server. But only the latter work, it's seem to be override the former. I have workaround for that issue by call the logic process message of the former in the latter handler then it's work but not really good. I wonder can I register multiple event handler like I describe above? Or can you add support for that feature? I think it's really essential.
Many thanks for your support and looking forward to hearing from you soon.

**Comment by aembke** [comment]
No problem, the next iteration was going to embed a full event emitter on the client. I'll try to get that released ASAP and then you'll have the full API surface for a [event emitter](https://nodejs.org/api/events.html).

**Comment by jerryc-nguyen** [comment]
thanks for your quick answer, that's sound great. Can't wait for your update, many thanks.
