### ISSUE TITLE
JSONP response parse error

### ISSUE THREAD

**Issue by GeerSwitch** [azuqua/token-sockjs-client#4]
This block, found in lines 132-141 of [`clients/browser/tokensock.js`](https://github.com/azuqua/token-sockjs-client/blob/master/clients/browser/tokensockjs.js) causes a problem when the `resp` argument is already an object.  
```
global[callbackKey] = function(resp) {
  global.document.body.removeChild(script);
  delete global[callbackKey];
  try{
    resp = JSON.parse(resp);
  }catch(e){
    return callback(new Error(resp || "Error making jsonp request!"));
  }
  callback(resp && resp.error ? resp.error : null, resp);
};
```
When the response is an object of the token, such as `{token: "612c9de2-9acf2-d4faa-9d4a-a5b7c8ac912b"}` (which mine was), the response should pass this data along to the callback.  The following hack allowed my Node TokenServer events to fire and respond.

```
global[callbackKey] = function(resp) {
  global.document.body.removeChild(script);
  delete global[callbackKey];
  
  // When the resp variable is an object, JSON.parse throws an error.
  if(typeof resp !== 'object'){
    try {
      resp = JSON.parse(resp);
    }catch(e){
      console.warn("Caught error: unable to parse response:", resp);
      return callback(new Error(resp || "Error making jsonp request!"));
    }
  }

  callback(resp && resp.error ? resp.error : null, resp);
};
```

**Comment by aembke** [comment]
Thanks for pointing this out. 

https://github.com/azuqua/token-sockjs-client/commit/75e3002f123197a611ea2a18042aef9c0409b714
